/*
 * minesweeper-server
 *
 * An API server for Minesweeper game
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MoveInfo struct {
	GameId string `json:"game_id"`
	X int32 `json:"x"`
	Y int32 `json:"y"`
}
