/*
 * minesweeper-server
 *
 * An API server for Minesweeper game
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Game struct {
	GameId string `json:"game_id,omitempty"`
	Status string `json:"status,omitempty"`
	BoardWidth int32 `json:"board_width,omitempty"`
	BoardHeight int32 `json:"board_height,omitempty"`
	MinesCount int32 `json:"mines_count,omitempty"`
	BoardState []string `json:"board_state,omitempty"`
	PrettyBoardState string `json:"pretty_board_state,omitempty"`
}
